name: "Podcast Generator"
author: "Vishwas"
description: "Generates a podcast episode based on user input."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: "Email address of the committer"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "Name of the committer"
    required: true
    default: ${{ github.actor }}